using System.Collections.Generic;

namespace DOLToolbox.Services
{
    public class ItemBonusService
    {
        public enum BonusType
        {
            Stat,
            StatCap,
            Resist,
            ResistCap,
            Skill,
            Focus,
            Toa,
            Mythical,
            Other
        }

        public class ItemBonus
        {
            public ItemBonus() { }

            public ItemBonus(int id, string value, BonusType type)
            {
                Id = id;
                Value = value;
                Type = type;
            }

            public BonusType Type { get; set; }
            public int Id { get; set; }
            public string Value { get; set; }
        }

        public static List<ItemBonus> Bonuses { get; } = new List<ItemBonus>
        {
            new ItemBonus(1, "Strength", BonusType.Stat),
            new ItemBonus(2, "Dexterity", BonusType.Stat),
            new ItemBonus(3, "Constitution", BonusType.Stat),
            new ItemBonus(4, "Quickness", BonusType.Stat),
            new ItemBonus(5, "Intelligence", BonusType.Stat),
            new ItemBonus(6, "Piety", BonusType.Stat),
            new ItemBonus(7, "Empathy", BonusType.Stat),
            new ItemBonus(8, "Charisma", BonusType.Stat),
            new ItemBonus(9, "Max Mana", BonusType.Stat),
            new ItemBonus(10, "Max Health", BonusType.Stat),
            new ItemBonus(11, "Body Resist", BonusType.Resist),
            new ItemBonus(12, "Cold Resist", BonusType.Resist),
            new ItemBonus(13, "Crush Resist", BonusType.Resist),
            new ItemBonus(14, "Energy Resist", BonusType.Resist),
            new ItemBonus(15, "Heat Resist", BonusType.Resist),
            new ItemBonus(16, "Matter Resist", BonusType.Resist),
            new ItemBonus(17, "Slash Resist", BonusType.Resist),
            new ItemBonus(18, "Spirit Resist", BonusType.Resist),
            new ItemBonus(19, "Thrust Resist", BonusType.Resist),
            new ItemBonus(20, "Two Handed Skill", BonusType.Skill),
            new ItemBonus(21, "Body Magic Skill", BonusType.Skill),
            new ItemBonus(22, "Chants Skill", BonusType.Skill),
            new ItemBonus(23, "Critical Strikes Skill", BonusType.Skill),
            new ItemBonus(24, "Cross Bows Skill", BonusType.Skill),
            new ItemBonus(25, "Crushing Skill", BonusType.Skill),
            new ItemBonus(26, "Death Servant Skill", BonusType.Skill),
            new ItemBonus(27, "Death Sight Skill", BonusType.Skill),
            new ItemBonus(28, "Dual Wield Skill", BonusType.Skill),
            new ItemBonus(29, "Earth Magic Skill", BonusType.Skill),
            new ItemBonus(30, "Enhancement Skill", BonusType.Skill),
            new ItemBonus(31, "Envenom Skill", BonusType.Skill),
            new ItemBonus(32, "Fire Magic Skill", BonusType.Skill),
            new ItemBonus(33, "Flexible Skill", BonusType.Skill),
            new ItemBonus(34, "Cold Magic Skill", BonusType.Skill),
            new ItemBonus(35, "Instruments Skill", BonusType.Skill),
            new ItemBonus(36, "Long Bows Skill", BonusType.Skill),
            new ItemBonus(37, "Matter Magic Skill", BonusType.Skill),
            new ItemBonus(38, "Mind Magic Skill", BonusType.Skill),
            new ItemBonus(39, "Painworking Skill", BonusType.Skill),
            new ItemBonus(40, "Parry Skill", BonusType.Skill),
            new ItemBonus(41, "Polearms Skill", BonusType.Skill),
            new ItemBonus(42, "Rejuvenation Skill", BonusType.Skill),
            new ItemBonus(43, "Shields Skill", BonusType.Skill),
            new ItemBonus(44, "Slashing Skill", BonusType.Skill),
            new ItemBonus(45, "Smiting Skill", BonusType.Skill),
            new ItemBonus(46, "Soulrending Skill", BonusType.Skill),
            new ItemBonus(47, "Spirit Magic Skill", BonusType.Skill),
            new ItemBonus(48, "Staff Skill", BonusType.Skill),
            new ItemBonus(49, "Stealth Skill", BonusType.Skill),
            new ItemBonus(50, "Thrusting Skill", BonusType.Skill),
            new ItemBonus(51, "Wind Magic Skill", BonusType.Skill),
            new ItemBonus(52, "Sword Skill", BonusType.Skill),
            new ItemBonus(53, "Hammer Skill", BonusType.Skill),
            new ItemBonus(54, "Axe Skill", BonusType.Skill),
            new ItemBonus(55, "Left Axe Skill", BonusType.Skill),
            new ItemBonus(56, "Spear Skill", BonusType.Skill),
            new ItemBonus(57, "Mending Skill", BonusType.Skill),
            new ItemBonus(58, "Augmentation Skill", BonusType.Skill),
            new ItemBonus(60, "Darkness Magic Skill", BonusType.Skill),
            new ItemBonus(61, "Suppression Magic Skill", BonusType.Skill),
            new ItemBonus(62, "Runecarving Skill", BonusType.Skill),
            new ItemBonus(63, "Stormcalling Skill", BonusType.Skill),
            new ItemBonus(64, "Beast Craft Skill", BonusType.Skill),
            new ItemBonus(65, "Light Magic Skill", BonusType.Skill),
            new ItemBonus(66, "Void Magic Skill", BonusType.Skill),
            new ItemBonus(67, "Mana Magic Skill", BonusType.Skill),
            new ItemBonus(68, "Composite Bow Skill", BonusType.Skill),
            new ItemBonus(69, "Battlesongs Skill", BonusType.Skill),
            new ItemBonus(70, "Enchantments Skill", BonusType.Skill),
            new ItemBonus(72, "Blades Skill", BonusType.Skill),
            new ItemBonus(73, "Blunt Skill", BonusType.Skill),
            new ItemBonus(74, "Piercing Skill", BonusType.Skill),
            new ItemBonus(75, "Large Weapon Skill", BonusType.Skill),
            new ItemBonus(76, "Mentalism Skill", BonusType.Skill),
            new ItemBonus(77, "Regrowth Skill", BonusType.Skill),
            new ItemBonus(78, "Nurture Skill", BonusType.Skill),
            new ItemBonus(79, "Nature Skill", BonusType.Skill),
            new ItemBonus(80, "Music Skill", BonusType.Skill),
            new ItemBonus(81, "Celtic Dual Skill", BonusType.Skill),
            new ItemBonus(82, "Celtic Spear Skill", BonusType.Skill),
            new ItemBonus(83, "Recurved Bow Skill", BonusType.Skill),
            new ItemBonus(84, "Valor Skill", BonusType.Skill),
            new ItemBonus(85, "Subterranean Skill", BonusType.Skill),
            new ItemBonus(86, "Bone Army Skill", BonusType.Skill),
            new ItemBonus(87, "Verdant Path Skill", BonusType.Skill),
            new ItemBonus(88, "Creeping Path Skill", BonusType.Skill),
            new ItemBonus(89, "Arboreal Path Skill", BonusType.Skill),
            new ItemBonus(90, "Scythe Skill", BonusType.Skill),
            new ItemBonus(91, "Thrown Weapons Skill", BonusType.Skill),
            new ItemBonus(92, "Hand to Hand Skill", BonusType.Skill),
            new ItemBonus(93, "Short Bow Skill", BonusType.Skill),
            new ItemBonus(94, "Pacification Skill", BonusType.Skill),
            new ItemBonus(95, "Savagery Skill", BonusType.Skill),
            new ItemBonus(96, "Nightshade Magic Skill", BonusType.Skill),
            new ItemBonus(97, "Pathfinding Skill", BonusType.Skill),
            new ItemBonus(98, "Summoning Magic Skill", BonusType.Skill),
            new ItemBonus(99, "Dementia Skill", BonusType.Skill),
            new ItemBonus(100, "Shadow Mastery Skill", BonusType.Skill),
            new ItemBonus(101, "Vampiiric Embrace Skill", BonusType.Skill),
            new ItemBonus(102, "Ethereal Shriek Skill", BonusType.Skill),
            new ItemBonus(103, "Phantasmal Wail Skill", BonusType.Skill),
            new ItemBonus(104, "Spectral Force Skill", BonusType.Skill),
            new ItemBonus(105, "Odins Will Skill", BonusType.Skill),
            new ItemBonus(106, "Cursing Skill", BonusType.Skill),
            new ItemBonus(107, "Hexing Skill", BonusType.Skill),
            new ItemBonus(108, "Witchcraft Skill", BonusType.Skill),
            new ItemBonus(109, "Mauler Staff Skill", BonusType.Skill),
            new ItemBonus(110, "Fist Wraps Skill", BonusType.Skill),
            new ItemBonus(111, "Power Strikes Skill", BonusType.Skill),
            new ItemBonus(112, "Magnetism Skill", BonusType.Skill),
            new ItemBonus(113, "Aura Manipulation Skill", BonusType.Skill),
            new ItemBonus(114, "Spectral Guard Skill", BonusType.Skill),
            new ItemBonus(115, "Archery Skill", BonusType.Skill),
            new ItemBonus(120, "Darkness Focus", BonusType.Focus),
            new ItemBonus(121, "Suppression Focus", BonusType.Focus),
            new ItemBonus(122, "Runecarving Focus", BonusType.Focus),
            new ItemBonus(123, "Spirit Magic Focus", BonusType.Focus),
            new ItemBonus(124, "Fire Magic Focus", BonusType.Focus),
            new ItemBonus(125, "Air Magic Focus", BonusType.Focus),
            new ItemBonus(126, "Cold Magic Focus", BonusType.Focus),
            new ItemBonus(127, "Earth Magic Focus", BonusType.Focus),
            new ItemBonus(128, "Light Magic Focus", BonusType.Focus),
            new ItemBonus(129, "Body Magic Focus", BonusType.Focus),
            new ItemBonus(130, "Matter Magic Focus", BonusType.Focus),
            new ItemBonus(132, "Mind Magic Focus", BonusType.Focus),
            new ItemBonus(133, "Void Magic Focus", BonusType.Focus),
            new ItemBonus(134, "Mana Magic Focus", BonusType.Focus),
            new ItemBonus(135, "Enchantments Focus", BonusType.Focus),
            new ItemBonus(136, "Mentalism Focus", BonusType.Focus),
            new ItemBonus(137, "Summoning Magic Focus", BonusType.Focus),
            new ItemBonus(138, "Bone Army Focus", BonusType.Focus),
            new ItemBonus(139, "Painworking Focus", BonusType.Focus),
            new ItemBonus(140, "Death Sight Focus", BonusType.Focus),
            new ItemBonus(141, "Death Servant Focus", BonusType.Focus),
            new ItemBonus(142, "Verdant Path Focus", BonusType.Focus),
            new ItemBonus(143, "Creeping Path Focus", BonusType.Focus),
            new ItemBonus(144, "Arboreal Path Focus", BonusType.Focus),
            new ItemBonus(145, "Max Speed", BonusType.Other),
            new ItemBonus(147, "Max Concentration", BonusType.Other),
            new ItemBonus(148, "Armor Factor", BonusType.Other),
            new ItemBonus(149, "Armor Absorption", BonusType.Other),
            new ItemBonus(150, "HealthRegenerationRate", BonusType.Other),
            new ItemBonus(151, "PowerRegenerationRate", BonusType.Other),
            new ItemBonus(152, "EnduranceRegenerationRate", BonusType.Other),
            new ItemBonus(153, "SpellRange", BonusType.Other),
            new ItemBonus(154, "ArcheryRange", BonusType.Other),
            new ItemBonus(155, "MeleeSpeed", BonusType.Other),
            new ItemBonus(156, "Acuity", BonusType.Stat),
            new ItemBonus(157, "Ethereal Shriek Focus", BonusType.Focus),
            new ItemBonus(158, "Phantasmal Wail Focus", BonusType.Focus),
            new ItemBonus(159, "Spectral Force Focus", BonusType.Focus),
            new ItemBonus(160, "Cursing Focus", BonusType.Focus),
            new ItemBonus(161, "Hexing Focus", BonusType.Focus),
            new ItemBonus(162, "Witchcraft Focus", BonusType.Focus),
            new ItemBonus(163, "AllMagicSkills", BonusType.Other),
            new ItemBonus(164, "AllMeleeWeaponSkills", BonusType.Other),
            new ItemBonus(165, "AllFocusLevels", BonusType.Other),
            new ItemBonus(166, "LivingEffectiveLevel", BonusType.Other),
            new ItemBonus(167, "AllDualWieldingSkills", BonusType.Other),
            new ItemBonus(168, "AllArcherySkills", BonusType.Other),
            new ItemBonus(169, "EvadeChance", BonusType.Other),
            new ItemBonus(170, "BlockChance", BonusType.Other),
            new ItemBonus(171, "ParryChance", BonusType.Other),
            new ItemBonus(172, "FatigueConsumption", BonusType.Other),
            new ItemBonus(173, "MeleeDamage", BonusType.Other),
            new ItemBonus(174, "RangedDamage", BonusType.Other),
            new ItemBonus(175, "FumbleChance", BonusType.Other),
            new ItemBonus(176, "MesmerizeDurationReduction", BonusType.Other),
            new ItemBonus(177, "StunDurationReduction", BonusType.Other),
            new ItemBonus(178, "SpeedDecreaseDurationReduction", BonusType.Other),
            new ItemBonus(179, "BladeturnReinforcement", BonusType.Other),
            new ItemBonus(180, "DefensiveBonus", BonusType.Other),
            new ItemBonus(181, "SpellFumbleChance", BonusType.Other),
            new ItemBonus(182, "NegativeReduction", BonusType.Other),
            new ItemBonus(183, "PieceAblative", BonusType.Other),
            new ItemBonus(184, "ReactionaryStyleDamage", BonusType.Other),
            new ItemBonus(185, "SpellPowerCost", BonusType.Other),
            new ItemBonus(186, "StyleCostReduction", BonusType.Other),
            new ItemBonus(187, "ToHitBonus", BonusType.Other),
            new ItemBonus(188, "Archery Speed", BonusType.Toa),
            new ItemBonus(189, "Arrow Recovery", BonusType.Toa),
            new ItemBonus(190, "Buff Effectiveness", BonusType.Toa),
            new ItemBonus(191, "Casting Speed", BonusType.Toa),
            new ItemBonus(192, "Death EXP Loss Redution", BonusType.Toa),
            new ItemBonus(193, "Debuff Effectiveness", BonusType.Toa),
            new ItemBonus(194, "Fatigue", BonusType.Toa),
            new ItemBonus(195, "Healing Effectiveness", BonusType.Toa),
            new ItemBonus(196, "Power Pool", BonusType.Toa),
            new ItemBonus(197, "Resist Pierce", BonusType.Toa),
            new ItemBonus(198, "Spell Damage", BonusType.Toa),
            new ItemBonus(199, "Spell Duration", BonusType.Toa),
            new ItemBonus(200, "Style Damage", BonusType.Toa),
            new ItemBonus(201, "Strength Cap", BonusType.StatCap),
            new ItemBonus(202, "Dexterity Cap", BonusType.StatCap),
            new ItemBonus(203, "Constitution Cap", BonusType.StatCap),
            new ItemBonus(204, "Quickness Cap", BonusType.StatCap),
            new ItemBonus(205, "Intelligence Cap", BonusType.StatCap),
            new ItemBonus(206, "Piety Cap", BonusType.StatCap),
            new ItemBonus(207, "Empathy Cap", BonusType.StatCap),
            new ItemBonus(208, "Charisma Cap", BonusType.StatCap),
            new ItemBonus(209, "Acuity Cap", BonusType.StatCap),
            new ItemBonus(210, "Max Health Cap", BonusType.StatCap),
            new ItemBonus(211, "Max Mana Cap", BonusType.StatCap),
            new ItemBonus(212, "WeaponSkill", BonusType.Other),
            new ItemBonus(213, "AllSkills", BonusType.Other),
            new ItemBonus(214, "CriticalMeleeHitChance", BonusType.Other),
            new ItemBonus(215, "CriticalArcheryHitChance", BonusType.Other),
            new ItemBonus(216, "CriticalSpellHitChance", BonusType.Other),
            new ItemBonus(217, "WaterSpeed", BonusType.Other),
            new ItemBonus(218, "SpellLevel", BonusType.Other),
            new ItemBonus(219, "MissHit", BonusType.Other),
            new ItemBonus(220, "KeepDamage", BonusType.Other),
            new ItemBonus(221, "Body Resist Cap", BonusType.ResistCap),
            new ItemBonus(222, "Cold Resist Cap", BonusType.ResistCap),
            new ItemBonus(223, "Crush Resist Cap", BonusType.ResistCap),
            new ItemBonus(224, "Energy Resist Cap", BonusType.ResistCap),
            new ItemBonus(225, "Heat Resist Cap", BonusType.ResistCap),
            new ItemBonus(226, "Matter Resist Cap", BonusType.ResistCap),
            new ItemBonus(227, "Slash Resist Cap", BonusType.ResistCap),
            new ItemBonus(228, "Spirit Resist Cap", BonusType.ResistCap),
            new ItemBonus(229, "Thrust Resist Cap", BonusType.ResistCap),
            new ItemBonus(230, "DPS", BonusType.Other),
            new ItemBonus(231, "MagicAbsorption", BonusType.Other),
            new ItemBonus(232, "CriticalHealHitChance", BonusType.Other),
            new ItemBonus(233, "MythicalSafeFall", BonusType.Mythical),
            new ItemBonus(234, "MythicalDiscumbering", BonusType.Mythical),
            new ItemBonus(235, "MythicalCoin", BonusType.Mythical),
            new ItemBonus(236, "MythicalStrCapBonus", BonusType.Mythical),
            new ItemBonus(237, "MythicalDexCapBonus", BonusType.Mythical),
            new ItemBonus(238, "MythicalConCapBonus", BonusType.Mythical),
            new ItemBonus(239, "MythicalQuiCapBonus", BonusType.Mythical),
            new ItemBonus(240, "MythicalIntCapBonus", BonusType.Mythical),
            new ItemBonus(241, "MythicalPieCapBonus", BonusType.Mythical),
            new ItemBonus(242, "MythicalEmpCapBonus", BonusType.Mythical),
            new ItemBonus(243, "MythicalChaCapBonus", BonusType.Mythical),
            new ItemBonus(244, "MythicalAcuCapBonus", BonusType.Mythical),
            new ItemBonus(247, "BountyPoints", BonusType.Other),
            new ItemBonus(248, "XpPoints", BonusType.Other),
            new ItemBonus(249, "Resist_Natural", BonusType.Other),
            new ItemBonus(250, "ExtraHP", BonusType.Other),
            new ItemBonus(251, "Conversion", BonusType.Other),
            new ItemBonus(252, "StyleAbsorb", BonusType.Other),
            new ItemBonus(253, "RealmPoints", BonusType.Other),
            new ItemBonus(254, "ArcaneSyphon", BonusType.Other),
            new ItemBonus(255, "LivingEffectiveness", BonusType.Other)
        };
    }
}